/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cjaxxknwzcpcowdjdhsr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqYXh4a253emNwY293ZGpkaHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzODY3NTcsImV4cCI6MjA3OTk2Mjc1N30.-Fkvu45Z6Uw2lLp6xKQH00-SC0_NOUoylH16N1k-fGo"